# AI/ML learn

This repo contains example and work of myself and other. Its goal is to keep trace of everything I learn about AI and related topics (numpy, pandas, DS...)
You can browse throught folder and code. View the commit history to know what I learn day by day...
Just learning in public basically...
